export enum InfrastructureExceptionType {
	BAD_REQUEST = "BAD_REQUEST",
	CONFLICT = "CONFLICT",
	NOT_FOUND = "NOT_FOUND",
	UNAUTHORIZED = "UNAUTHORIZED",
	FORBIDDEN = "FORBIDDEN",
	INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}
