name: Deploy API in Docker

on:
  workflow_run:
    workflows: ["Test API"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git Semantic Version
        id: version
        uses: PaulHatch/semantic-version@v4.0.3
        with:
          major_pattern: "major:"
          minor_pattern: "feat:"
          format: "${major}.${minor}.${patch}-prerelease${increment}"

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        env:
          NEW_VERSION: ${{ steps.version.outputs.version }}
          DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO }}
        run: |
          echo "Building image with tags: $DOCKERHUB_REPO:$NEW_VERSION and $DOCKERHUB_REPO:latest"
          docker build -t $DOCKERHUB_REPO:$NEW_VERSION -t $DOCKERHUB_REPO:latest .

      - name: Push Docker image
        env:
          NEW_VERSION: ${{ steps.version.outputs.version }}
          DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO }}
        run: |
          docker push $DOCKERHUB_REPO:$NEW_VERSION
          docker push $DOCKERHUB_REPO:latest
